### ISSUE TITLE
A badge (shield) for standard PHP packages

### ISSUE THREAD

**Issue by odan** [php-pds/skeleton#16]
Are you planning a badges/shields service for packages which complies with the Standard PHP package skeleton?

https://github.com/badges/shields

**Comment by pmjones** [comment]
I had not planned on one. Would you like to put one together? I suppose it should be flexible enough to allow not just for pds/skeleton, but also for other pds/* publications.

**Comment by odan** [comment]
I've written small PHP script to see if it's possible. 
I think I could implement such a badge service for pds/skeleton. It would also be possible to offer special badges for other pds/* publications. The only problem is the server infrastructure (hosting, AWS, Domain(s)) etc...

**Comment by odan** [comment]
"RawGit serves raw files directly from GitHub with proper Content-Type headers."
https://rawgit.com/

Here is an example badge. The text is just an idea and could be changed.
You can copy/paste this markdown to the php-pds/skeleton readme.md or create a new repo e.g. 
 `php-pds/php-pds-badge`

**PDS Skeleton Badge**
[![PDS Compatible](https://cdn.rawgit.com/odan/php-pds-badge/cfa62d0a/php-pds-skeleton-badge.svg)](https://github.com/php-pds/skeleton)

**Source:**
https://github.com/odan/php-pds-badge
https://gist.github.com/odan/ee035f508e8d38b4c4f9b2666ea75c78

**Comment by pmjones** [comment]
@odan Neat! I if a separate repo for all possible badges (php-pds/badges ?) would make sense, or if keeping the badge with the publication (say, in php-pds/skeleton/public/badge.png) would be better.

Second, it should probably say "[ pds | skeleton ]" rather than "[ pds | compatible ]", in anticipation of future publications.

Also, how did you generate the badge in the first place?

Thanks for thinking of this!

**Comment by odan** [comment]
Here is the new version with: [ pds | skeleton ] in green and blue.
https://github.com/odan/php-pds-badge

`php-pds/badges` would be a good repo name.

> Also, how did you generate the badge in the first place?

I've made this badge(s) with a small PHP script (still beta).

**Comment by erunion** [comment]
@odan You have plans to submit this into the Shields.io repo?

**Comment by odan** [comment]
@erunion Yes, shields.io is a good idea. The question is, which color? 
Brightgreen or blue?

[![PDS Compatible](https://img.shields.io/badge/pds-skeleton-brightgreen.svg?style=flat)](https://github.com/php-pds/skeleton) [![PDS Compatible](https://img.shields.io/badge/pds-skeleton-brightgreen.svg?style=flat-square)](https://github.com/php-pds/skeleton)

[![PDS Compatible](https://img.shields.io/badge/pds-skeleton-blue.svg?style=flat)](https://github.com/php-pds/skeleton) [![PDS Compatible](https://img.shields.io/badge/pds-skeleton-blue.svg?style=flat-square)](https://github.com/php-pds/skeleton)

**Comment by pmjones** [comment]
Blue. The green looks like a "pass/fail" color.

**Comment by pmjones** [comment]
OK, @odan , what do I need to do now? Create the repo, put that image in it, and start telling people to link it from rawgithub?

**Comment by odan** [comment]
@pmjones I think it would be better to use the links from shields.io.

https://img.shields.io/badge/pds-skeleton-blue.svg?style=flat-square
https://img.shields.io/badge/pds-skeleton-blue.svg?style=flat

I've updated my repo: https://github.com/odan/php-pds-badge
It would be good to have an official PDS Badge repo (`php-pds/badges` ?) for this and the next badges.

After that, I add this new badge to the shields.io repo:
https://github.com/badges/shields/blob/master/index.html

**Comment by pmjones** [comment]
@odan Roger that. I will handle it today/tomorrow and ping you when done. Thanks a lot for your efforts on this!

**Comment by pmjones** [comment]
@odan I have created the php-pds/badges repo, and invited you for "write" access. Do what you think is right in that repo, and I'll review. Thanks again for your interest and effort!

**Comment by pmjones** [comment]
@odan Looks nice! If nothing else is needed, I'll close this issue. Soon I'll update the php-pds site to note the badge availability. Thanks a ton for this!

**Comment by odan** [comment]
Thank you :-)

You can close this issue now.
