### ISSUE TITLE
[Suggestion] Validate filesystem

### ISSUE THREAD

**Issue by afilina** [php-pds/skeleton#20]
It would be useful to ship this package with a validator based on the recommendations. A simple compliance report would then be displayed to the user.

I'm happy to help create this, if people agree to this feature.

**Comment by pmjones** [comment]
DO IT

**Comment by pmjones** [comment]
As a side note, keep it at no-dependencies. Plain PHP. The "weight" on this should be the lowest possible.

**Comment by afilina** [comment]
Understood.

**Comment by pmjones** [comment]
Thanks :-)

It occurs to me that the skeleton-research "compliance.php" script might be a useful starting point. (/me shrugs)

**Comment by afilina** [comment]
I was actually just reading that script.

**Comment by afilina** [comment]
@pmjones Almost done. Can we agree on the following three report states for each element?

- Command-line executables directory not present (yellow)
- /bin present (green)
- Incorrect /cli present (red)

**Comment by pmjones** [comment]
Closing this as "fixed" by #21. We can continue to iterate on the code as needed.
