### ISSUE TITLE
[Suggestion] Skeleton generator

### ISSUE THREAD

**Issue by afilina** [php-pds/skeleton#23]
Add a compliant skeleton generator. It should not assume that the directory structure is empty.

**Comment by pmjones** [comment]
DO IT

**Comment by afilina** [comment]
On it. I'll also organize the validator code a bit and put the binary in the parent project's bin/

**Comment by pmjones** [comment]
Right on.

I very much appreciate your work here; thanks.

**Comment by afilina** [comment]
Should the files (LICENSE, README, etc.) have a .md extension by default?

**Comment by sepehr** [comment]
[Yeoman](http://yeoman.io/)?

**Comment by pmjones** [comment]
This appears to be complete. Thanks @afilina !
