### ISSUE TITLE
Some Interfacing 

### ISSUE THREAD

**Issue by dracony** [php-pds/skeleton#26]
A small idea I have would be allow for some sort of an  optional `.skeleton.php` file that would make it possible to redefine the structure. Could look something like this:

```php
return new class implements SkeletonInterface
{
     public function sourceDirectory()
     {
          return '/src';
     }, //...
}
```

You get the idea. This would make it possible for projects with existing structure that they can't just change to still make the directory mapping known to some components that need it.

For example bower allows specifying `main` files in the bower.json instead of relying on a predefined component structure.

**Comment by Revisor** [comment]
Why? What for?

**Comment by dracony** [comment]
Good question ))

For example so that some automatic code linting tool can easily find your sources, etc.

**Comment by calevans** [comment]
Honestly, I am not in favor of this. If you rename your src file to something else, then you aren't in compliance. 

-1

Cheers! :)
=C=

**Comment by pmjones** [comment]
/me furrows brow

I don't see the point of redefining the structure; the whole idea here is that there's a standard skeleton, already agreed-upon by a large number of existing packages.

**Comment by dracony** [comment]
Alright, I guess I really took the cake with useless complexity with this)
