### ISSUE TITLE
License rules do not respect the LGPL

### ISSUE THREAD

**Issue by Bilge** [php-pds/skeleton#28]
* LGPL is a two-part license (the GPL plus the lesser extensions). However, these naïve rules assume the license must be a single file.
* According to the [GNU how-to](https://www.gnu.org/licenses/gpl-howto.html) the license should be named COPYING but these ignorant rules state it must be named LICENSE.
* [GitHub's license-detection software does not support the LGPL being specified in a file named anything other than `COPYING.LESSER`](https://github.com/benbalter/licensee/issues/143). These arbitrary rules state the extension should be lower-case and only used to indicate file format.

In light of these poorly-researched rules you should not be making rules about licenses at all. That is, rather than attempting to make amends, simply remove any rules regarding licensing because you cannot construct such rules in a useful manner, particularly when you spare no effort to research the subject.

**Comment by pmjones** [comment]
Hi @Bilge --

> According to the GNU how-to the license should be named COPYING

Yes; I see the GNU how-to uses the phrasing "usually" and "should" for that recommendation. The filename LICENSE is therefore not prohibited by the how-to.

> GitHub's license-detection software

Noted; however, this publication tries to be non-tooling-specific.

> rather than attempting to make amends, simply remove any rules regarding licensing

Hard to make that happen, per the research, which shows LICENSE files occurring at a high rate.

But, and contra your preference, there might be a way to add a "MAY" clause to the LICENSE rule, specifically allowing for 2 files when particular licenses "MUST" be in 2 files.

**Comment by Bilge** [comment]
>Hard to make that happen, per the research, which shows LICENSE files occurring at a high rate.

This makes absolutely no sense. You have proven no relevant research has been conducted, you have merely pulled some stats and observed some usage patterns. Putting that aside, the reason you should be removing all rules about licensing is because there are no meaningful rules to be applied to licenses because they are freestyle text. Turning empirical patterns into rules doesn't add any value, it just tells those who are conforming to continue and those who are not to become conformist. Such an attitude has no place in licensing.

**Comment by pmjones** [comment]
> you have merely pulled some stats and observed some usage patterns

Yes, that's correct. 

> there are no meaningful rules to be applied to licenses because they are freestyle text

Also correct. For what it's worth, the publication says nothing about the text of the license, only that the file must be named "LICENSE".

> Such an attitude has no place in licensing.

The publication isn't about "licensing" per se, only about PHP package skeletons.

(FWIW, I do appreciate your prior support on other topics.)

**Comment by Bilge** [comment]
>(FWIW, I do appreciate your prior support on other topics.)

I don't know what you're talking about as I've never supported this effort, but if you're not inclined to remove licensing rules there's no value to this discussion, and for that reason, I'm closing it.

**Comment by Revisor** [comment]
For what it's worth, I think "COPYING" is a really bad name for a license file and I see no reason why a file named "LICENSE" couldn't contain the text of a GPL. If it's a two-part license (what would be the reason for this?), the first part can still be in the file called LICENSE.

**Comment by OdinVex** [comment]
Apparently the validator only looks for the first license-like file it can encounter and assumes that is the license for everything. Some of us use `COPYING` *and* `LICENSE`, not to mention some files are being mistaken for licensing. The desire to match by regex for licenses instead of using the pre-determined defacto of `COPYING` and `LICENSE` (etc) is baffling.
