### ISSUE TITLE
A /data directory

### ISSUE THREAD

**Issue by adamculp** [php-pds/skeleton#31]
It seems to be common place among many PHP applications to have a standard /data directory. Since I do not see it in the skeleton, and some of the linked research examples, I assume it was discussed and eliminated from consideration. Thoughts?

**Comment by pmjones** [comment]
Per the research, a `data/` directory is not as common as you might think. Its frequency is only about 1%; cf <https://github.com/php-pds/skeleton_research/blob/1.x/results/05-dirs.txt#L102> .

Having said that, a `data/` directory is not prohibited by the standard; the publication just does not explicitly state a standard name for that kind of directory.

**Comment by adamculp** [comment]
Fair point. I think we can close this, but thought it warranted enough attention to be added to the history for future generations. Thanks.
