### ISSUE TITLE
resource -> res, docs -> doc, tests -> test

### ISSUE THREAD

**Issue by Yousha** [php-pds/skeleton#33]
I think we should change these terms:

**resources -> res** (like bin, config, doc, etc...)
tests -> test
docs -> doc

Like most of languages...

**Comment by pawelzny** [comment]
I don't like your idea about "resources" -> "res"
"res" is also shortcut from "response" and could be misleading.

But I might agree about changing plural forms to singular to unify directories names.

**Comment by pmjones** [comment]
The research disagrees with you: the plural forms are the ones most-used.

https://github.com/php-pds/skeleton_research
