### ISSUE TITLE
Where does the database go?

### ISSUE THREAD

**Issue by fulldecent** [php-pds/skeleton#37]
SQLite databases can be included directly in the PHP project repository.

Here is one example: https://github.com/fulldecent/19-questions (local/database.db).

Is there or should there be a defined location for such files?

Note: configuration files and databases are similar in that they will have different versions between production and QA deployments. Also, they will both be excluded in .gitignore.

**Comment by pmjones** [comment]
In the research, SQLite was very uncommon. You can see yourself at <https://github.com/php-pds/skeleton_research/blob/1.x/results/addendum-dirs.txt>. When you find for "sql" directories there are only around 250 entries from across 110,000 packages. "Database" fares a little better, at around 1000 or so, but that's still pretty uncommon. (Similar results for top-level files as well: <https://github.com/php-pds/skeleton_research/blob/1.x/results/addendum-files.txt>)

As such, the standard neither specifies nor prohibits SQLite databases in any particular location.

**Comment by fulldecent** [comment]
Got it, thanks for pointing me to good data.
