### ISSUE TITLE
Package binaries MUST BE located in /bin

### ISSUE THREAD

**Issue by raphaelstolt** [php-pds/skeleton#4]
If a package provides a CLI, it's binary or binaries __MUST BE__ located under the `/bin` directory and __MUST BE__ configured as a [vendor binary](https://getcomposer.org/doc/articles/vendor-binaries.md#what-is-a-vendor-binary-) in the package its `composer.json`.

**Comment by cxj** [comment]
This sounds like a good idea to me!

**Comment by Revisor** [comment]
Maybe too nitpicking, but what if a new packager arrives? Or Composer dies?

**Comment by theofidry** [comment]
Disagree, we are talking of recommendations not laws. Besides you may have a bin for convenience but not wanting to configure it as a vendor binary.

**Comment by Revisor** [comment]
Ah, I misunderstood the issue. Are you talking about the Composer setting `bin` (as in defining binaries meant for the client), or `bin-dir` (directory for binaries from package dependencies)?

I would disagree with both cases anyway.

**Comment by theofidry** [comment]
Actually I misread your first sentence, I agree that a binary provided by a library **should** be in `/bin`. I don't think `must` is an appropriate word in a recommendation like this one still.

**Comment by raphaelstolt** [comment]
@theofidry Could live with a __SHOULD__, though I really dislike packages having their binaries in the root directory of the package like for example [Construct](https://github.com/jonathantorres/construct).

@Revisor Were talking about the Composer setting/configuration `bin`.

It __SHOULD__ be configured as a vendor binary for Composer packages providing a CLI. When Composer dies or a new better packager arrives the skeleton/standard should and can be refined.

**Comment by pmjones** [comment]
So, two problems here:

1. I think it's best that the standard be non-tooling-specific. It should not mention of Git/Hg/Svn/Whatever as version-control systems except as examples, and it should not mention Composer/Pear/Whatever as package managers except as examples. Any task that can't be done in one of them, is a reason to leave that task out of the standard.

2. Although I personally (and probably lots of others, maybe even a majority) would like to see all PHP code in `src/`, all binaries in `bin/`, etc., and not in the root directory, the research does not support that as a rule for the standard. There are lots of people putting source code in the root.

Now, having said that, it is *possible* that a later version of the "skeleton" standard may add language to the effect that you MAY or SHOULD or MUST keep source/tests/binaries/whatever in their respective directories, and not in the root, but that's definitely for later and not for now.

Do you see where I'm coming from there?

**Comment by pmjones** [comment]
@raphaelstolt et al -- any further thoughts on this? I am leaning toward closing this as "not supported by the research" but I want to make sure I'm not missing an important point from your reasoning.

**Comment by raphaelstolt** [comment]
Feel free to close this one too.

**Comment by pmjones** [comment]
Very good; thanks.
