### ISSUE TITLE
Question: Concrete PDS-Skeleton Example

### ISSUE THREAD

**Issue by tbreuss** [php-pds/skeleton#44]
I come up with a question to you. Maybe you have some tips or recommendations?

I was starting a package  with a concrete PHP package skeleton based on your PDS Skeleton:
<https://github.com/tbreuss/php-package-skeleton>

The idea is to have some kind of a boilerplate that enables you to quickly start a new project. In contrast to PDS it contains concrete implementations. 

What do you think about this?

**Comment by ghost** [comment]
Like this?

https://github.com/audreyr/cookiecutter
