### ISSUE TITLE
IDEA: Considered submitting as a PSR?

### ISSUE THREAD

**Issue by davidjeddy** [php-pds/skeleton#48]
I like that this project is codifying what is being observed in the eco-system rather than documenting an idea and trying to get people to buy into it.

Have the team considered submitting this for consideration as a PSR for libraries?

**Comment by odan** [comment]
This would be great for the PHP ecosystem. As far as I know the big players like [Laravel](https://laravel.com/docs/5.7/structure) and [Symfony](http://fabien.potencier.org/symfony4-directory-structure.html) are already "compatible".

**Comment by pmjones** [comment]
If the question is one of "getting it into the ecosystem", then it's already there.

**Comment by davidjeddy** [comment]
More one of submitting this project for `official` recognition of a community wide recommendation.
