### ISSUE TITLE
CONTRIBUTING file location might differ for GitHub based package repositories

### ISSUE THREAD

**Issue by raphaelstolt** [php-pds/skeleton#5]
When developing with GitHub based package repositories a common location of the `CONTRIBUTING` file is `.github/CONTRIBUTING`.

**Comment by Revisor** [comment]
I don't think packages should be locked to Github conventions. They can be hosted on Gitlab, Bitbucket or elsewhere.

**Comment by raphaelstolt** [comment]
Did not say that it should be locked to GitHub conventions, but that it should be considered. Though GitLab stays [close ](https://gitlab.com/help/user/project/description_templates.md) to the convention with a different directory structure. When defining a PHP package standard / skeleton you can't neglect supportive tooling of the SCM systems.

**Comment by pmjones** [comment]
Hey @raphaelstolt -- man, you really are reviewing and thinking about this stuff. Thanks for the concentrated effort. :-)

I get you on respecting the spaces claimed by particular services (GitHub, GitLab, etc). I think current draft of the standard does make allowance for that. Note that the `CONTRIBUTING` file, for example, is not a required file. The draft says only that *if* a top-level file is provided as a guideline for contributors, *then* it must be named CONTRIBUTING.  If you don't have a top-level file of that kind, you are not out of compliance with the standard.

Further, the draft says that there may be other directories for other purposes not described by the standard. A `.github/` definitely falls in the "other unspecified" category, so having one does not put you out of compliance.

Does all that make sense?

**Comment by ravage84** [comment]
@pmjones Problem with the current draft is that, if you have such a file, it __MUST__ be named ``CONTRIBUTIN(.md)`` and __MUST__ be in the root folder.

https://github.com/php-pds/skeleton#summary

> A package MUST use the following names for the following kinds of directories and files:

> CONTRIBUTING    # guidelines for contributors

https://github.com/php-pds/skeleton#contributing

> If the package provides a file that describes how to contribute to the package, it MUST be named CONTRIBUTING.

The way the current draft is writen, it forces you to have this file **under this name & at that location**, if you want to have one.
The only chance you would have, is to have **a copy** in the service specific folder.

**Comment by pmjones** [comment]
>  it MUST be named CONTRIBUTIN(.md) and MUST be in the root folder.

Hi @ravage84 -- apparently the summary gives an impression it should not. I will modify it.

Also, even though the section is labeled "Root-Level Files", it might be more clear to repeat that in the text of each rule (i.e., "root-level file" and not just "file").

That should help to make the intent more clear: that *if* you have a top-level file or directory, serving the described purpose, *then* is must be named X. (If it's not present at all, or if it is present at some place other than the root, then the standard has nothing to say.)

I'll ping you again after the changes.

**Comment by pmjones** [comment]
@ravage84 The draft now emphasizes in each rule that it applies to root-level elements: https://github.com/php-pds/skeleton/commit/42b0109c3eb0c8a811e9216ebd2a5061ea18af8f

I will attempt to rephrase the summary so that the overall intent is more clear; i.e., that it applies only to root-level files that are provided for the given intent.

**Comment by pmjones** [comment]
After several tries, I think the prefatory summary sentence is sufficiently clear and succinct. I can re-open this issue if you still think a modification is necessary.
