### ISSUE TITLE
What is better?, resources, res or assets?

### ISSUE THREAD

**Issue by DevKhris** [php-pds/skeleton#52]
Normally i tend to use "assets" otherelse than "resources" because in some of the projects i've been, some of the teams get confused about what the "resources" folder is, for some is for the styling stuff like css or sass or images only and others think is for packages like vendor, there's a way for better standard for naming this folder?

**Comment by odan** [comment]
Personally I distinguish between "assets" and "resources". 

The "resources/" directory contains **internal** files that the application needs to process something, for example: xml schemas (xsd), fonts (for TCPDF), internal images like logos for PDF's, translation files, etc...

The "assets/" directory contains public available and "compiled" or "transpiled" files from webpack. This directory is public available and I put it under `public/` directory, e.g. `public/assets/`.

Only the `vendor/` directory should contain (composer) packages.
