### ISSUE TITLE
Contributors and maintainers SHALL have tooling support

### ISSUE THREAD

**Issue by raphaelstolt** [php-pds/skeleton#6]
It __SHOULD__ be __dead__ easy for contributors and maintainers to run tests, fix coding standard violations, and do new releases (obvs. maintainers only). 

It's __RECOMMENDED__ to provide these via Composer scripts where suitable and feasible.

**Comment by theofidry** [comment]
Whilst I agree with the intent, I think this repo responsibility stops at giving tips on how to achieve that. How much tooling you are willing to provide for your maintainers depends a lot on whether or not you want to make contribution more accessible, but it highly depends on how far you are ready to go for that, it's not always worth it.

>It's RECOMMENDED to provide these via Composer scripts where suitable and feasible.

It's only **one** way, bash scripts, PHP scripts, Make or whatever, as long as it's easy and makes sense :)

**Comment by pmjones** [comment]
@raphaelstolt This sounds like it might be out of scope for a "skeleton top-level directory and file names" standard. Also, it's Composer-specific, and the standard would to well to avoid references to specific tooling (except as examples: "version control systems, such as Git or Hg"). Do you see what I mean here?

**Comment by pmjones** [comment]
@raphaelstolt I am leaning toward closing this as "out of scope" (as well as "tooling-specific"), but I want to make sure there are not further arguments in the issue's favor. Any other thoughts here?

**Comment by raphaelstolt** [comment]
Feel free to close it, as it doesn't relate to the intend of the standard skeleton.
