### ISSUE TITLE
Public assets (js, css, images)

### ISSUE THREAD

**Issue by odan** [php-pds/skeleton#7]
This is a really great project. I like this standard, because it fits to my personal experience und taste.
Is this standard only for "Root-Level Directories"? What about the public assets?

**Example 1**
```
public/js/              # java-script files
public/css/             # css files
public/images/          # image files
public/fonts/           # font files
public/icons/           # icon files
```

**Example 2** (like Bootstrap)
```
public/assets/js/       # java-script files
public/assets/css/      # css files
public/assets/img/      # image files
public/assets/fonts/    # font files
public/assets/ico/      # icon files
````

**Comment by pmjones** [comment]
Hi @odan -- glad you like it. :-)

The standard is only for top-level directory & file names. Public assets, to be delivered on the web somehow, do go in `public/` -- but as to the *subdirectory* therein, the standard does not specify. So you could have `public/css/`, `public/assets/css/`, or anything else you like -- the standard does not go that far.

Does that help?

**Comment by odan** [comment]
Yes, thank you! :+1:
