### ISSUE TITLE
Uniform directory naming scheme

### ISSUE THREAD

**Issue by raphaelstolt** [php-pds/skeleton#9]
This one might be tad controversial, but hey we're shaping a standard. Directories like `bin` and `config` should be also be pluralised like `docs` or `tests`.

**Comment by Revisor** [comment]
I disagree, the current names are the most used and make sense.

I have never seen `bins` or `configs`.

**Comment by guenti** [comment]
I think the folder docs should be named doc, like /usr/share/doc etc. It's more unix like and a de facto standard. tests is okay.

**Comment by raphaelstolt** [comment]
It's true that the reading of `bins` and `configs` feels very strange.
